export const SELECT_CLIENT = "SELECT_CLIENT";
export const ADD_CLIENT = "ADD_CLIENT";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const RECEIVE_CLIENT = "RECIEVE_CLIENT";
export const RECEIVE_DELETED_CLIENT = "RECEIVE_DELETED_CLIENT";

export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const RECEIVE_PRODUCT = "RECIEVE_PRODUCT";
export const RECEIVE_DELETED_PRODUCT = "RECEIVE_DELETED_PRODUCT";

export const SELECT_GROUP = "SELECT_GROUP";
export const ADD_GROUP = "ADD_GROUP";
export const EDIT_GROUP = "EDIT_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const RECEIVE_GROUP = "RECIEVE_GROUP";
export const RECEIVE_DELETED_GROUP = "RECEIVE_DELETED_GROUP";

export const SELECT_PERMISSION = "SELECT_PERMISSION";
export const SELECT_PERMISSION_CATEGORY = "SELECT_PERMISSION_CATEGORY";

export const SELECT_CUSTOM_VALUE = "SELECT_CUSTOM_VALUE";
export const SELECT_CUSTOM_TYPE = "SELECT_CUSTOM_TYPE";

export const SELECT_CLIENT_PERMISSION = "SELECT_CLIENT_PERMISSION";
export const ADD_CLIENT_PERMISSION = "ADD_CLIENT_PERMISSION";
export const EDIT_CLIENT_PERMISSION = "EDIT_CLIENT_PERMISSION";
export const DELETE_CLIENT_PERMISSION = "DELETE_CLIENT_PERMISSION";
export const RECEIVE_CLIENT_PERMISSION = "RECIEVE_CLIENT_PERMISSION";
export const RECEIVE_DELETED_CLIENT_PERMISSION =
  "RECEIVE_DELETED_CLIENT_PERMISSION";

export const SELECT_PRODUCT_PERMISSION = "SELECT_PRODUCT_PERMISSION";
export const ADD_PRODUCT_PERMISSION = "ADD_PRODUCT_PERMISSION";
export const EDIT_PRODUCT_PERMISSION = "EDIT_PRODUCT_PERMISSION";
export const DELETE_PRODUCT_PERMISSION = "DELETE_PRODUCT_PERMISSION";
export const RECEIVE_PRODUCT_PERMISSION = "RECIEVE_PRODUCT_PERMISSION";
export const RECEIVE_DELETED_PRODUCT_PERMISSION =
  "RECEIVE_DELETED_PRODUCT_PERMISSION";

export const SELECT_GROUP_PERMISSION = "SELECT_GROUP_PERMISSION";
export const ADD_GROUP_PERMISSION = "ADD_GROUP_PERMISSION";
export const EDIT_GROUP_PERMISSION = "EDIT_GROUP_PERMISSION";
export const DELETE_GROUP_PERMISSION = "DELETE_GROUP_PERMISSION";
export const RECEIVE_GROUP_PERMISSION = "RECIEVE_GROUP_PERMISSION";
export const RECEIVE_DELETED_GROUP_PERMISSION =
  "RECEIVE_DELETED_GROUP_PERMISSION";

export const SELECT_PRODUCT_USER_TYPE_PERMISSION =
  "SELECT_PRODUCT_USER_TYPE_PERMISSION";
export const ADD_PRODUCT_USER_TYPE_PERMISSION =
  "ADD_PRODUCT_USER_TYPE_PERMISSION";
export const EDIT_PRODUCT_USER_TYPE_PERMISSION =
  "EDIT_PRODUCT_USER_TYPE_PERMISSION";
export const DELETE_PRODUCT_USER_TYPE_PERMISSION =
  "DELETE_PRODUCT_USER_TYPE_PERMISSION";
export const RECEIVE_PRODUCT_USER_TYPE_PERMISSION =
  "RECIEVE_PRODUCT_USER_TYPE_PERMISSION";
export const RECEIVE_DELETED_PRODUCT_USER_TYPE_PERMISSION =
  "RECEIVE_DELETED_PRODUCT_USER_TYPE_PERMISSION";

export const SELECT_CLIENT_CUSTOM_VALUE_PERMISSION =
  "SELECT_CLIENT_CUSTOM_VALUE_PERMISSION";
export const ADD_CLIENT_CUSTOM_VALUE_PERMISSION =
  "ADD_CLIENT_CUSTOM_VALUE_PERMISSION";
export const EDIT_CLIENT_CUSTOM_VALUE_PERMISSION =
  "EDIT_CLIENT_CUSTOM_VALUE_PERMISSION";
export const DELETE_CLIENT_CUSTOM_VALUE_PERMISSION =
  "DELETE_CLIENT_CUSTOM_VALUE_PERMISSION";
export const RECEIVE_CLIENT_CUSTOM_VALUE_PERMISSION =
  "RECIEVE_CLIENT_CUSTOM_VALUE_PERMISSION";
export const RECEIVE_DELETED_CLIENT_CUSTOM_VALUE_PERMISSION =
  "RECEIVE_DELETED_CLIENT_CUSTOM_VALUE_PERMISSION";

export const SELECT_PRODUCT_CUSTOM_VALUE_PERMISSION =
  "SELECT_PRODUCT_CUSTOM_VALUE_PERMISSION";
export const ADD_PRODUCT_CUSTOM_VALUE_PERMISSION =
  "ADD_PRODUCT_CUSTOM_VALUE_PERMISSION";
export const EDIT_PRODUCT_CUSTOM_VALUE_PERMISSION =
  "EDIT_PRODUCT_CUSTOM_VALUE_PERMISSION";
export const DELETE_PRODUCT_CUSTOM_VALUE_PERMISSION =
  "DELETE_PRODUCT_CUSTOM_VALUE_PERMISSION";
export const RECEIVE_PRODUCT_CUSTOM_VALUE_PERMISSION =
  "RECIEVE_PRODUCT_CUSTOM_VALUE_PERMISSION";
export const RECEIVE_DELETED_PRODUCT_CUSTOM_VALUE_PERMISSION =
  "RECEIVE_DELETED_PRODUCT_CUSTOM_VALUE_PERMISSION";

export const SELECT_GROUP_CUSTOM_VALUE_PERMISSION =
  "SELECT_GROUP_CUSTOM_VALUE_PERMISSION";
export const ADD_GROUP_CUSTOM_VALUE_PERMISSION =
  "ADD_GROUP_CUSTOM_VALUE_PERMISSION";
export const EDIT_GROUP_CUSTOM_VALUE_PERMISSION =
  "EDIT_GROUP_CUSTOM_VALUE_PERMISSION";
export const DELETE_GROUP_CUSTOM_VALUE_PERMISSION =
  "DELETE_GROUP_CUSTOM_VALUE_PERMISSION";
export const RECEIVE_GROUP_CUSTOM_VALUE_PERMISSION =
  "RECIEVE_GROUP_CUSTOM_VALUE_PERMISSION";
export const RECEIVE_DELETED_GROUP_CUSTOM_VALUE_PERMISSION =
  "RECEIVE_DELETED_GROUP_CUSTOM_VALUE_PERMISSION";
